# Generated by Django 3.0.5 on 2021-04-25 09:21

from django.db import migrations

from utils.csv_to_db import fill_db


def main(apps, schema_editor):
    title = apps.get_model('titles', 'title')
    model_config = (
        ('data/genre.csv', apps.get_model('titles', 'genre')),
        ('data/category.csv', apps.get_model('titles', 'category')),
        ('data/titles.csv', apps.get_model('titles', 'title')),
        ('data/genre_title.csv', title.genres.through),
    )

    for config in model_config:
        fill_db(*config)


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(main),
    ]
